### ISSUE TITLE
FR - enhanced output

### ISSUE THREAD

**Issue by rotty3000** [kangasta/yaml_requests#36]
I'd like to propose an enhancement to the output with the goal of improving debugging.

- add output options for request headers and request body (to make sure the request is as we expect it)
- add directional markers (as in `curl` to express request `>` vs. response `<`)
- automatically format body based on known content types (like `json+`)

e.g. here is a modified output of `tst/plans/build_queue.yml` where the only plan change is:
```patch
@@ -18,10 +18,16 @@ requests:
   post:
     url: "{{ base_url }}/queue/{{ response.json().0.id }}/init"
     json:
       node: "{{ node }}"
   register: build_create
+  output:
+  - request_headers
+  - request_body
+  - response_headers
+  - response_body
+  - foo
 - name: Get queued items
   get:
     url: "{{ base_url }}/queue"
   assert:
   - name: Queue is shorter than initially


```

The output is as follows:
![image](https://github.com/kangasta/yaml_requests/assets/146764/85fd1d5e-89a2-47e1-a45c-78e8fdaac0a4)

I have a PR queued up if there's interest.

**Comment by kangasta** [comment]
Thanks for the enhancement idea and implementation! I'll take a look at the PR and let's get that merged in.
